project_id = "tntxwxajgfrqoddqijum"

[functions.create-super-admin]
verify_jwt = false

[functions.create-user-with-email]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true

[functions.delete-account]
verify_jwt = true